apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::562239681881:user/terraform-user
      username: terraform-user
      groups:
        - system:masters