name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Start FastAPI app in background
        run: |
          python -m uvicorn api.main:app --host 0.0.0.0 --port 8000 &
          sleep 5  # wait for the server to start

      - name: Test /docs endpoint
        run: curl -f http://127.0.0.1:8000/docs