name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          IMAGE_URI=562239681881.dkr.ecr.eu-north-1.amazonaws.com/loan-api:latest
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
            --region eu-north-1 \
            --name loan-api-eks \
            --kubeconfig kubeconfig

      - name: Deploy updated image to EKS
        env:
          KUBECONFIG: kubeconfig
        run: |
          IMAGE_URI=562239681881.dkr.ecr.eu-north-1.amazonaws.com/loan-api:latest
          kubectl set image deployment/loan-api loan-api=$IMAGE_URI

      - name: Force rollout of updated deployment
        env:
          KUBECONFIG: ./kubeconfig
        run: |
          kubectl rollout restart deployment/loan-api